name: vehicle
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter==1.0.0
  - matplotlib==3.1.1
  - numpy==1.16.5
  - scikit-learn==0.21.2
  - scipy==1.3.1
  - tensorboard==1.14.0
  - tensorflow==1.14.0
  - pandas==1.1.3
  - pillow==8.0.1
  - opencv==4.1.1
  - python==3.7.0
  - keras==2.3.1
  